/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasguipbotaufik;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class PembayaranToko extends javax.swing.JFrame {

    /**
     * Creates new form PembayaranToko
     */
    public PembayaranToko() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TokoMamah = new javax.swing.JLabel();
        NamaBarang = new javax.swing.JLabel();
        Jumlah = new javax.swing.JLabel();
        TotalPembelian = new javax.swing.JLabel();
        CbBox = new javax.swing.JComboBox<>();
        Harga = new javax.swing.JLabel();
        Diskon = new javax.swing.JLabel();
        TotalPembayaran = new javax.swing.JLabel();
        UangPembayaran = new javax.swing.JLabel();
        UangKembalian = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnHitungKembalian = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtTotalPembelian = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        txtTotalPembayaran = new javax.swing.JTextField();
        txtUangPembayaran = new javax.swing.JTextField();
        txtUangKembalian = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TokoMamah.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TokoMamah.setText("TOKO RAIHAN");

        NamaBarang.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        NamaBarang.setText("Nama Barang");

        Jumlah.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Jumlah.setText("Jumlah");

        TotalPembelian.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TotalPembelian.setText("Total pembelian");

        CbBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang", "Pensil", "Pena", "Buku", "Penggaris" }));
        CbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbBoxActionPerformed(evt);
            }
        });

        Harga.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Harga.setText("Harga");

        Diskon.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Diskon.setText("Diskon");

        TotalPembayaran.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TotalPembayaran.setText("Total Pembayaran");

        UangPembayaran.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        UangPembayaran.setText("Uang Pembayaran");

        UangKembalian.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        UangKembalian.setText("Uang Kembalian");

        btnHitung.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnHitung.setText("Hitung\n");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnHitungKembalian.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnHitungKembalian.setText("Hitung Kembalian");
        btnHitungKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungKembalianActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnReset.setText("Reset\n");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnKeluar.setText("Keluar\n");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaBarang)
                    .addComponent(Jumlah)
                    .addComponent(TotalPembelian)
                    .addComponent(Diskon)
                    .addComponent(TotalPembayaran)
                    .addComponent(UangPembayaran)
                    .addComponent(UangKembalian))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TokoMamah)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTotalPembelian, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJumlah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CbBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUangKembalian, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUangPembayaran, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalPembayaran)
                                    .addComponent(txtDiskon))
                                .addGap(58, 58, 58)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Harga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHitungKembalian)
                            .addComponent(btnHitung)
                            .addComponent(btnReset)
                            .addComponent(btnKeluar))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TokoMamah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(NamaBarang)
                                            .addComponent(CbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Harga)
                                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Jumlah)
                                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TotalPembelian)
                                            .addComponent(txtTotalPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Diskon)
                                            .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnHitung))
                                .addGap(38, 38, 38)
                                .addComponent(TotalPembayaran))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnHitungKembalian)
                                .addComponent(txtTotalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addComponent(UangPembayaran))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReset)
                        .addComponent(txtUangPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UangKembalian, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnKeluar)
                        .addComponent(txtUangKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbBoxActionPerformed
        int brg = (int)CbBox.getSelectedIndex();
        switch (brg){
            case 1: txtHarga.setText("7500");break;
            case 2 : txtHarga.setText("10000");break;
            case 3 : txtHarga.setText("15000");break;
            case 4 : txtHarga.setText("8000");break;
        }
    }//GEN-LAST:event_CbBoxActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
  try {
        int harga = Integer.parseInt(txtHarga.getText());
        int jumlah = Integer.parseInt(txtJumlah.getText());
 
        int total = harga * jumlah;
        txtTotalPembelian.setText(Integer.toString(total));

        double diskon = 0;
        if (jumlah > 10) {
            diskon = 0.1 * total; 
        }

        double bayar = total - diskon;

        txtDiskon.setText(Double.toString(diskon));
        txtTotalPembayaran.setText(Double.toString(bayar));
        
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk Harga dan Jumlah!", "Error", JOptionPane.ERROR_MESSAGE);
    }                                        
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnHitungKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungKembalianActionPerformed
         try {
            double uangPembayaran = Double.parseDouble(txtUangPembayaran.getText());
            double totalPembayaran = Double.parseDouble(txtTotalPembayaran.getText());

            if (uangPembayaran < totalPembayaran) {
                double uangKurang = totalPembayaran - uangPembayaran;
                JOptionPane.showMessageDialog(this, "Uang pembayaran kurang sebesar Rp. " + uangKurang, "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else {
                double uangKembalian = uangPembayaran - totalPembayaran;
                txtUangKembalian.setText(String.valueOf(uangKembalian));
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Input salah! Pastikan uang pembayaran diisi dengan angka.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnHitungKembalianActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    CbBox.setSelectedIndex(0);     
    txtHarga.setText("");            
    txtJumlah.setText("");            
    txtTotalPembelian.setText("");  
    txtDiskon.setText("");           
    txtTotalPembayaran.setText("");   
    txtUangPembayaran.setText("");   
    txtUangKembalian.setText("");     
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin keluar?", 
        "Konfirmasi Keluar", 
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0); 
    }
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PembayaranToko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbBox;
    private javax.swing.JLabel Diskon;
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel Jumlah;
    private javax.swing.JLabel NamaBarang;
    private javax.swing.JLabel TokoMamah;
    private javax.swing.JLabel TotalPembayaran;
    private javax.swing.JLabel TotalPembelian;
    private javax.swing.JLabel UangKembalian;
    private javax.swing.JLabel UangPembayaran;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnHitungKembalian;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTotalPembayaran;
    private javax.swing.JTextField txtTotalPembelian;
    private javax.swing.JTextField txtUangKembalian;
    private javax.swing.JTextField txtUangPembayaran;
    // End of variables declaration//GEN-END:variables
}
