/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasguipboraihan;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class PolaPerulangan extends javax.swing.JFrame {

    /**
     * Creates new form PolaPerulangan
     */
    public PolaPerulangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        labelPilih = new javax.swing.JLabel();
        cbPilih = new javax.swing.JComboBox<>();
        btnProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaHasil = new javax.swing.JTextArea();
        txtPertama = new javax.swing.JTextField();
        txtKedua = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJudul.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelJudul.setText("POLA PERULANGAN");

        label1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        label1.setText("Angka pertama");

        label2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        label2.setText("Angka kedua");

        labelPilih.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelPilih.setText("Pilih pola");

        cbPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih pola", "pola 1", "pola 2", "pola 3", "pola 4", "pola 5", "pola 6", "pola 7" }));

        btnProses.setText("proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        areaHasil.setColumns(20);
        areaHasil.setRows(5);
        jScrollPane1.setViewportView(areaHasil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(labelJudul))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelPilih)
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKedua)
                            .addComponent(txtPertama)
                            .addComponent(cbPilih, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btnProses)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(txtPertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(txtKedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPilih)
                    .addComponent(cbPilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
       try{
           int a=Integer.parseInt(txtPertama.getText());
           int b=Integer.parseInt(txtKedua.getText());
           int pil=(int)cbPilih.getSelectedIndex();
           StringBuilder pola= new StringBuilder("tampilkan pola \n\n");
           
           switch(pil) {
    case 1:
        for (int i = 1; i <= a; i++) {
            for (int j = 1; j <= b; j++) {
                pola.append("*");
            }
            pola.append("\n");
        }
        break;

    case 2:
        for (int i = 1; i <= a; i++) {
            for (int j = 1; j <= i; j++) {
                pola.append("*");
            }
            pola.append("\n");
        }
        break;

    case 3:
        for (int i = a; i >= 1; i--) {
            for (int j = 1; j <= i; j++) {
                pola.append("*");
            }
            pola.append("\n");
        }
        break;

    case 4:
        for (int i = 1; i <= a; i++) {
            for (int j = a; j > i; j--) {
                pola.append("  ");
            }
            for (int j = 1; j <= (2 * i - 1); j++) {
                pola.append("*");
            }
            pola.append("\n");
        }
        break;

    case 5:
        for (int i = 1; i <= a; i++) {
            for (int j = a; j > i; j--) {
                pola.append(" ");
            }
            for (int j = 1; j <= (2 * i - 1); j++) {
                pola.append("*");
            }
            pola.append("\n");
        }
        for (int i = a - 1; i >= 1; i--) {
            for (int j = a; j > i; j--) {
                pola.append("  ");
            }
            for (int j = 1; j <= (2 * i - 1); j++) {
                pola.append("*");
            }
            pola.append("\n");
        }
        break;

    case 6:
        for (int i = 1; i <= a; i++) {
            for (int j = 1; j <= b; j++) {
                if (i == 1 || i == a || j == 1 || j == b) {
                    pola.append("*");
                } else {
                    pola.append("  ");
                }
            }
            pola.append("\n");
        }
        break;

    case 7:
        for (int i = 1; i <= a; i++) {
            for (int j = 1; j <= b; j++) {
                if ((i + j) % 2 == 0) {
                    pola.append("*");
                } else {
                    pola.append("  ");
                }
            }
            pola.append("\n");
        }
        break;

    default:
        pola.append("Pilihan tidak valid!");
        break;
}areaHasil.setText(pola.toString());
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(this,"masukkan angka valid","input error",JOptionPane.ERROR_MESSAGE);
       }finally{
           JOptionPane.showMessageDialog(this,"data berhasil disimpan","input sukses",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PolaPerulangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaHasil;
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox<String> cbPilih;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelPilih;
    private javax.swing.JTextField txtKedua;
    private javax.swing.JTextField txtPertama;
    // End of variables declaration//GEN-END:variables
}
